# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 19:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(default='Seattle', max_length=255)),
                ('state', localflavor.us.models.USStateField(default='WA', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', localflavor.us.models.PhoneNumberField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('gender', models.CharField(choices=[('M', 'Men Only'), ('W', 'Women Only'), ('A', 'Any')], default='A', max_length=255)),
                ('upper_age', models.PositiveSmallIntegerField(default=150, validators=[django.core.validators.MaxValueValidator(150)])),
                ('lower_age', models.PositiveSmallIntegerField(default=0)),
                ('us_citizens_only', models.BooleanField()),
                ('sober_only', models.BooleanField()),
                ('case_managers', models.BooleanField()),
                ('open_24_hours', models.BooleanField()),
                ('service_animals', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('accepts_sex_offenders', models.BooleanField()),
                ('accepts_criminals', models.BooleanField()),
                ('accepts_incarcerated', models.BooleanField()),
                ('languages', models.ManyToManyField(to='searchlist.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='services',
            field=models.ManyToManyField(to='searchlist.Service'),
        ),
    ]
