# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.AddField(
            model_name='resource',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='state',
            field=localflavor.us.models.USStateField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='resource',
            name='street',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(default='', max_length=10),
        ),
    ]
