# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='age_range',
        ),
        migrations.AlterField(
            model_name='resource',
            name='main_category',
            field=models.CharField(choices=[('Crisis', 'Crisis'), ('Addiction', 'Addiction'), ('Childcare', 'Childcare'), ('Youth Services', 'Youth Services'), ('Veteran', 'Veteran'), ('Rehabilitation', 'Rehabilitation'), ('Mental/Physical Disability', 'Mental/Physical Disability'), ('Education', 'Education'), ('Employment', 'Employment'), ('Finances', 'Finances'), ('Clothing/Housewares', 'Clothing/Housewares'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Shelter', 'Shelter'), ('Legal', 'Legal'), ('Identification', 'Identification'), ('Spiritual', 'Spiritual')], max_length=25),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ratings',
            field=models.CharField(blank=True, default='one badge', max_length=25, null=True),
        ),
    ]
