# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:29
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
    ]
