# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0002_auto_20170726_2120'),
        ('searchlist', '0002_auto_20170726_2039'),
    ]

    operations = [
    ]
