# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0003_resource_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='family_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
