# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0004_resource_family_friendly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='accepts_criminals',
            new_name='accepts_criminal_records',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='accepts_sex_offenders',
            new_name='accepts_sex_offender_records',
        ),
    ]
