# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0004_resource_family_friendly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='accepts_criminals',
            new_name='accepts_criminal_records',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='accepts_sex_offenders',
            new_name='accepts_sex_offender_records',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='service_animals',
        ),
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='fax_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
