# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0004_auto_20170726_2337'),
    ]

    operations = [
    ]
