# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0005_merge_20170727_0024'),
        ('searchlist', '0005_auto_20170727_0323'),
    ]

    operations = [
    ]
