# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0006_remove_resource_service_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
