# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0007_auto_20170727_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='ratings',
        ),
    ]
