# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 03:16
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0007_resource_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='fax_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
    ]
