# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0012_auto_20170728_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='city',
            field=models.CharField(default=b'Seattle', max_length=256),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='resource',
            name='main_category',
            field=models.CharField(choices=[(b'Crisis', b'Crisis'), (b'Addiction', b'Addiction'), (b'Childcare', b'Childcare'), (b'Youth Services', b'Youth Services'), (b'Veteran', b'Veteran'), (b'Rehabilitation', b'Rehabilitation'), (b'Mental/Physical Disability', b'Mental/Physical Disability'), (b'Education', b'Education'), (b'Employment', b'Employment'), (b'Finances', b'Finances'), (b'Clothing/Housewares', b'Clothing/Housewares'), (b'Food', b'Food'), (b'Healthcare', b'Healthcare'), (b'Shelter', b'Shelter'), (b'Legal', b'Legal'), (b'Identification', b'Identification'), (b'Spiritual', b'Spiritual')], max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='org_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='state',
            field=localflavor.us.models.USStateField(default=b'', max_length=2),
        ),
        migrations.AlterField(
            model_name='resource',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
