# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 01:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0014_auto_20170920_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='main_category',
        ),
        migrations.AddField(
            model_name='resource',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MD', 'Medical Care'), ('HS', 'Housing'), ('CS', 'Counseling'), ('CZ', 'Citizenship'), ('JB', 'Job Assistance'), ('SB', 'Substance Recovery'), ('DV', 'Fleeing Domestic Violence'), ('HT', 'Fleeing Human Trafficking'), ('CM', 'Case Management'), ('MH', 'Mental Health Treatment'), ('TR', 'Trauma'), ('HL', 'Hotline'), ('WF', 'Welfare'), ('CL', 'Clothing'), ('TE', 'Technology'), ('DT', 'Dental'), ('PH', 'Pharmacy'), ('TP', 'Transportation'), ('WI', 'Winter'), ('ST', 'Storage'), ('CR', 'Crisis'), ('AD', 'Addiction'), ('CH', 'Childcare'), ('YS', 'Youth Services'), ('VE', 'Veteran'), ('RE', 'Rehabilitation'), ('MP', 'Mental/Physical Disability'), ('ED', 'Education'), ('EM', 'Employment'), ('FI', 'Financal Assistance'), ('SU', 'Clothing/Housewares'), ('FO', 'Food'), ('HC', 'Healthcare'), ('SH', 'Shelter'), ('LE', 'Legal Assistance'), ('ID', 'Identification'), ('SP', 'Spiritual')], default='None', max_length=110),
        ),
    ]
