# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models


from searchlist.models import ResourceTag


TAGS = {
    'gender': ['any', 'women', 'men'],
    'age_restriction': ['yes', 'no'],
    'language': ['spanish', 'russian', 'ukranian', 'german',
                 'french', 'somali', 'vietnamese', 'chinese'],
    'citizenship': ['any', 'us_only'],
    'sobriety': ['any', 'sober'],
    'cost': ['free', 'some_free', 'not_free'],
    'case_manager': ['yes', 'no'],
    'counselor': ['yes', 'no'],
    'other': ['trauma', 'trafficking', 'domestic_violence', 'legal', 'lgbtqia'
              'short_term', 'long_term', 'welfare_assistance', 'meals',
              'electronics', 'transportation', 'winter', 'storage', 'showers',
              'criminal_record', 'refugee_assistance', 'pets_welcome']
}


def create_tags(apps, schema_editor):
    """Tag factory."""
    for family, tags in TAGS.items():
        for tag in tags:
            ResourceTag.objects.get_or_create(family=family, value=tag)


def delete_tags(apps, schema_editor):
    """Tag destroyer."""
    for family, tags in TAGS.items():
        for tag in tags:
            try:
                ResourceTag.objects.get(family=family, value=tag).delete()
            except ResourceTag.ObjectDoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('searchlist', '0018_auto_20171114_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='searchlist.ResourceTag'),
        ),
        migrations.RunPython(create_tags, delete_tags)
    ]
