# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('center', 'center'), ('shelter', 'shelter'), ('food', 'food'), ('clinic', 'clinic')], default='center', max_length=25, null=True)),
                ('ratings', models.CharField(choices=[('one badge', 'one badge'), ('two badge', 'two badge'), ('three badge', 'three badge')], default='one badge', max_length=25, null=True)),
                ('age_range', models.CharField(choices=[('<=17', '<=17'), ('18-25', '18-25'), ('>26', '>26')], max_length=25, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
