# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170725_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
