# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_resource_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
